In [1]:
import numpy as np

## Creating Subsitution Matrix

In [2]:
sbox = np.array([i for i in range(256)], dtype=np.uint8)
np.random.shuffle(sbox)
sbox

array([ 66,  72, 138,  77, 195,  59,  73,  93,   3,  20, 143, 187,  48,
         4, 106, 205,  81, 141,  55, 133, 176, 127, 116, 226,  89, 135,
        95,  64,  29, 102,  18,  98,  58, 186, 151,   7,  85,  80,  31,
       104, 243,  13,  94,  83, 139, 228,   2,  92, 223, 161, 134, 103,
        49, 156,  87, 107,  44, 180,  28,  14,   1,  17, 219,  90, 252,
       208,  62, 125, 211, 192,  56, 188, 193, 241,  97, 144,  15, 229,
       222, 232, 160, 146, 128,  91,  22, 198, 206,  96, 110, 247, 238,
       212,  39,  67, 158, 137, 249, 136, 170,  27, 153, 159, 175,  24,
        61, 148, 233, 105,  42, 167, 202, 203,  11,  86,  68, 113, 237,
       100, 248, 162, 168, 179, 149,  19, 194,  84,   8, 122, 184,  12,
       224, 108, 204,  40, 225,  53, 197,   5, 221, 173, 130, 155,  50,
       118, 129, 112,  65, 101, 216,  23,  32, 131, 199, 239, 124, 178,
        38, 150, 245, 183,  63,  25, 142,  57,  37, 157,  47, 190, 200,
         0, 209, 120,   6, 169, 231, 172, 109, 152,  21,  46,  1

In [3]:
sbox_inv = np.zeros(256, dtype=np.uint8)
for i in range(256):
    sbox_inv[sbox[i]] = i

In [4]:
sbox_inv

array([169,  60,  46,   8,  13, 137, 172,  35, 126, 243, 180, 112, 129,
        41,  59,  76, 209,  61,  30, 123,   9, 178,  84, 149, 103, 161,
       182,  99,  58,  28, 203,  38, 150, 241, 234, 216, 205, 164, 156,
        92, 133, 246, 108, 231,  56, 238, 179, 166,  12,  52, 142, 230,
       210, 135, 219,  18,  70, 163,  32,   5, 220, 104,  66, 160,  27,
       146,   0,  93, 114, 206, 251, 252,   1,   6, 225, 227, 197,   3,
       195, 228,  37,  16, 224,  43, 125,  36, 113,  54, 186,  24,  63,
        83,  47,   7,  42,  26,  87,  74,  31, 233, 117, 147,  29,  51,
        39, 107,  14,  55, 131, 176,  88, 221, 145, 115, 217, 201,  22,
       215, 143, 213, 171, 193, 127, 248, 154,  67, 229,  21,  82, 144,
       140, 151, 249,  19,  50,  25,  97,  95,   2,  44, 200,  17, 162,
        10,  75, 211,  81, 181, 105, 122, 157,  34, 177, 100, 188, 141,
        53, 165,  94, 101,  80,  49, 119, 226, 196, 250, 189, 109, 120,
       173,  98, 214, 175, 139, 247, 102,  20, 245, 155, 121,  5

## Creating Permutation Matrix

In [5]:
pbox1 = np.array([i for i in range(128)], dtype=np.uint8)
np.random.shuffle(pbox1)
pbox1

array([ 67,  73,  56,   8,  13,  65,  21,  18,  12, 127,  92,  69, 100,
        53,  86, 116, 122,  88,  24,  30,  47,  43, 103,  82,  98,  99,
       104,  36,  46,  87, 120,  94,  68, 118,  22,  49,  35,  44,  77,
        57,  17, 112,  55,  62, 123,  97,  25,  20,  71, 117,  93,  83,
        16,  59, 113,  32, 110,  26,  60,  11, 119,  51,  63,  91,  45,
        39,  76,  95, 109,  89, 101, 121, 107, 114,   6,  15,  66,  78,
        72,  50,  48,  38,  31, 105,   4,  52,   9,  14,  19,  70,   2,
        27,  96,   5,   3,   0,  75,  29,  80,  42,  79,   7,  61,  74,
       111, 115,  34,  84, 106,   1,  33, 108, 102, 125,  23,  58,  85,
        28,  37,  81,  54, 124,  40,  10,  41,  90, 126,  64], dtype=uint8)

In [6]:
pbox1_inv = np.zeros(128, dtype=np.uint8)
for i in range(128):
    pbox1_inv[pbox1[i]] = i
pbox1_inv

array([ 95, 109,  90,  94,  84,  93,  74, 101,   3,  86, 123,  59,   8,
         4,  87,  75,  52,  40,   7,  88,  47,   6,  34, 114,  18,  46,
        57,  91, 117,  97,  19,  82,  55, 110, 106,  36,  27, 118,  81,
        65, 122, 124,  99,  21,  37,  64,  28,  20,  80,  35,  79,  61,
        85,  13, 120,  42,   2,  39, 115,  53,  58, 102,  43,  62, 127,
         5,  76,   0,  32,  11,  89,  48,  78,   1, 103,  96,  66,  38,
        77, 100,  98, 119,  23,  51, 107, 116,  14,  29,  17,  69, 125,
        63,  10,  50,  31,  67,  92,  45,  24,  25,  12,  70, 112,  22,
        26,  83, 108,  72, 111,  68,  56, 104,  41,  54,  73, 105,  15,
        49,  33,  60,  30,  71,  16,  44, 121, 113, 126,   9], dtype=uint8)

In [7]:
pbox2 = np.array([i for i in range(128)], dtype=np.uint8)
np.random.shuffle(pbox2)
pbox2

array([ 68,  42,  95,  28, 117,  55,  30, 115,  78,  38,  86, 123, 103,
        13, 113,  74, 116,  10,  71,  79,   7,  93,  26, 109,  37,   5,
        58,  39,  70, 112, 118,  87,  41,  80,  17,  61,  35, 127,  73,
         0,   9, 106,  40,  65,  48,  53,   2, 114,  66,  59,  64,  92,
         8,  45,  23,  22,  18,  75,  63, 126,  97,  15,  72,  50,  29,
        51,  54,  88,  44, 108, 125,  36,  60, 104,  96,   1, 119, 124,
       100,  34,  90,  52,  57,  11,  19,  99,  82,   3,  49,  94,  25,
         4,  24,  62,  67,  76,  69, 101, 120, 107,  81,  47,  85,  56,
        43, 122, 110,  31,  89,  98, 111,  20,  77,  32,  83, 102,  27,
        33,  21,  46, 121, 105,  16,  91,  14,   6,  84,  12], dtype=uint8)

In [8]:
pbox2_inv = np.zeros(128, dtype=np.uint8)
for i in range(128):
    pbox2_inv[pbox2[i]] = i
pbox2_inv

array([ 39,  75,  46,  87,  91,  25, 125,  20,  52,  40,  17,  83, 127,
        13, 124,  61, 122,  34,  56,  84, 111, 118,  55,  54,  92,  90,
        22, 116,   3,  64,   6, 107, 113, 117,  79,  36,  71,  24,   9,
        27,  42,  32,   1, 104,  68,  53, 119, 101,  44,  88,  63,  65,
        81,  45,  66,   5, 103,  82,  26,  49,  72,  35,  93,  58,  50,
        43,  48,  94,   0,  96,  28,  18,  62,  38,  15,  57,  95, 112,
         8,  19,  33, 100,  86, 114, 126, 102,  10,  31,  67, 108,  80,
       123,  51,  21,  89,   2,  74,  60, 109,  85,  78,  97, 115,  12,
        73, 121,  41,  99,  69,  23, 106, 110,  29,  14,  47,   7,  16,
         4,  30,  76,  98, 120, 105,  11,  77,  70,  59,  37], dtype=uint8)

## Generating Random 4x4

In [41]:
val = ([np.random.randint(0,255) for i in range(12)])
multiplier = np.random.randint(0,255)
val += [multiplier * np.random.randint(0,255) % 256 for i in range(4)]

np.random.huffle(mat)
mat.reshape((4,4))

array([[131, 147,  16,  66],
       [131, 147,  16,  66],
       [131, 147,  16,  66],
       [131, 147,  16,  66]], dtype=uint8)

In [31]:
np.linalg.inv([[1,2],[1,2]])

LinAlgError: Singular matrix